# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param x RObject to be checked
#' @return Either a NumericVector or an Error depending upon the type checked
#' @export
NumVec <- function(x) {
    .Call(`_typed_NumVec`, x)
}

